// Package utils provides shared utility functions used throughout the dflow CLI.
//
// It includes helpers for:
//
//   - Reading and writing the .dflow.yaml configuration file
//   - Console output formatting (e.g., colors, emojis, status messages)
//   - Signal handling for graceful termination (e.g., Ctrl+C)
//
// The branching domain itself — the configuration schema, branch types and
// finish planning — lives in the pure `pkg/flow` package; this package only
// performs the file I/O around it.
package utils

import (
	"fmt"
	"os"

	"github.com/yepizrene-devoost/dflow/pkg/flow"
	"gopkg.in/yaml.v3"
)

const bannerToConfig = `
#
#               ██████╗ ███████╗██╗      ██████╗ ██╗    ██╗
#               ██╔══██╗██╔════╝██║     ██╔═══██╗██║    ██║
#               ██║  ██║█████╗  ██║     ██║   ██║██║ █╗ ██║
#               ██║  ██║██╔══╝  ██║     ██║   ██║██║███╗██║
#               ██████╔╝██║     ███████╗╚██████╔╝╚███╔███╔╝
#               ╚═════╝ ╚═╝     ╚══════╝ ╚═════╝  ╚══╝╚══╝ 

#            dflow config file - autogenerated by 'dflow init'
`

// LoadConfig reads and parses the .dflow.yaml configuration file
// from the current working directory (or DFLOW_CWD if set).
// Returns a populated flow.Config struct or an error.
func LoadConfig() (*flow.Config, error) {
	dir := os.Getenv("DFLOW_CWD")
	if dir == "" {
		dir, _ = os.Getwd()
	}

	path := dir + string(os.PathSeparator) + ".dflow.yaml"

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read .dflow.yaml: %w", err)
	}

	var cfg flow.Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("error parsing .dflow.yaml: %v", err)
	}

	return &cfg, nil
}

// SaveConfig writes the given flow.Config struct to a .dflow.yaml file
// in the current working directory (or DFLOW_CWD if set).
//
// The file will be overwritten if it already exists.
// A banner header is included for identification.
func SaveConfig(cfg *flow.Config) error {
	yamlData, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("error generating YAML: %v", err)
	}

	finalContent := []byte(bannerToConfig + "\n" + string(yamlData))

	dir := os.Getenv("DFLOW_CWD")
	if dir == "" {
		dir, _ = os.Getwd()
	}

	path := dir + string(os.PathSeparator) + ".dflow.yaml"

	if err := os.WriteFile(path, finalContent, 0644); err != nil {
		return fmt.Errorf("error writing .dflow.yaml: %v", err)
	}

	return nil
}
