// Package utils provides shared utility functions used throughout the dflow CLI.
//
// It includes helpers for:
//
//   - Reading and writing the .dflow.yaml configuration file
//   - Console output formatting (e.g., colors, emojis, status messages)
//   - Signal handling for graceful termination (e.g., Ctrl+C)
//
// The branching domain itself — the configuration schema, branch types and
// finish planning — lives in the pure `pkg/flow` package; this package only
// performs the file I/O around it.
package utils

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/yepizrene-devoost/dflow/pkg/flow"
	"github.com/yepizrene-devoost/dflow/pkg/repository"
	"gopkg.in/yaml.v3"
)

const bannerToConfig = `
#
#               ██████╗ ███████╗██╗      ██████╗ ██╗    ██╗
#               ██╔══██╗██╔════╝██║     ██╔═══██╗██║    ██║
#               ██║  ██║█████╗  ██║     ██║   ██║██║ █╗ ██║
#               ██║  ██║██╔══╝  ██║     ██║   ██║██║███╗██║
#               ██████╔╝██║     ███████╗╚██████╔╝╚███╔███╔╝
#               ╚═════╝ ╚═╝     ╚══════╝ ╚═════╝  ╚══╝╚══╝ 

#            dflow config file - autogenerated by 'dflow init'
`

// LoadConfig reads and parses the repository's canonical .dflow.yaml
// configuration file. DFLOW_CWD selects the repository context when set.
// Returns a populated flow.Config struct or an error.
func LoadConfig() (*flow.Config, error) {
	context, err := repository.Discover()
	if err != nil {
		return nil, fmt.Errorf("failed to discover repository context: %w", err)
	}

	data, err := os.ReadFile(context.ConfigPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read .dflow.yaml: %w", err)
	}

	var cfg flow.Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("error parsing .dflow.yaml: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return nil, fmt.Errorf("invalid .dflow.yaml: %w", err)
	}

	return &cfg, nil
}

// SaveConfig writes the given flow.Config struct to the repository's
// canonical .dflow.yaml configuration file. DFLOW_CWD selects the repository
// context when set.
//
// The file will be overwritten if it already exists.
// A banner header is included for identification.
func SaveConfig(cfg *flow.Config) error {
	if cfg == nil {
		return fmt.Errorf("cannot save nil config")
	}

	context, err := repository.Discover()
	if err != nil {
		return fmt.Errorf("failed to discover repository context: %w", err)
	}

	yamlData, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("error generating YAML: %w", err)
	}

	finalContent := []byte(bannerToConfig + "\n" + string(yamlData))

	temporary, err := os.CreateTemp(filepath.Dir(context.ConfigPath), ".dflow.yaml.tmp-*")
	if err != nil {
		return fmt.Errorf("error creating temporary .dflow.yaml: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0644); err != nil {
		temporary.Close()
		return fmt.Errorf("error setting temporary .dflow.yaml permissions: %w", err)
	}
	if _, err := temporary.Write(finalContent); err != nil {
		temporary.Close()
		return fmt.Errorf("error writing temporary .dflow.yaml: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		temporary.Close()
		return fmt.Errorf("error syncing temporary .dflow.yaml: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("error closing temporary .dflow.yaml: %w", err)
	}
	if err := os.Rename(temporaryPath, context.ConfigPath); err != nil {
		return fmt.Errorf("error replacing .dflow.yaml: %w", err)
	}

	return nil
}
